modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="prelude" #mandatory

version="1.18.2-0.3.6.release" #mandatory

displayName="jurassic: prelude" #mandatory
displayURL= "https://github.com/rexbr3615/modprelude , https://www.curseforge.com/minecraft/mc-mods/jurassick-prelude"

logoFile="PRTS.png" #optional
# A text field displayed in the mod UI
credits="rexbr," #optional
# A text field displayed in the mod UI
authors="rexbr," #optional

description='''

the jurassic prelude adds a variety of extinct creature on minecraft.
the mod was created by a group of friends who like dinosaurs and other prehistoric creatures that inhabited our planet's past, Jurassic Prelude adds a variety of them, and this is just the beginning

a big thanks you to you who played this mod!!

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.prelude]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.prelude]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.prelude]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.39,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.prelude]]
     modId="mekanism"
     mandatory=true
     versionRange="[10.2.5,)"
     ordering="BEFORE"
     side="BOTH"







